server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo
    username: root
    password: mysql@2020
    driver-class-name: com.mysql.cj.jdbc.Driver

 #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: AFSiuriefdkjk
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 1000

# 指定 session 保存方式
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: session

#spring jpa 配置
  jpa:
    show-sql: true